### ISSUE TITLE
`disease` takes ~34s to run on a trivial example when built in debug mode

### ISSUE THREAD

**Issue by jwasinger** [quilt/etk#111]
Trying `disease --hex-file my_hex_file.hex` where the file contains `0x6000` takes awhile on my machine.

I have isolated it to: https://github.com/quilt/etk/blob/master/etk-4byte/src/lib.rs#L44-L52 .

**Comment by SamWilsn** [comment]
Does it spin forever, or for several seconds? Uncompressing the selector database takes a few moments.
