### ISSUE TITLE
labels are not adjusted when including files

### ISSUE THREAD

**Issue by holiman** [quilt/etk#137]
We have a main app, `a.etk `:
```
# This is the main application. 
push2 0x0000
# Now we load some sub-application
%include("b.etk")
```
And the `b.etk`:
``` 
# This is the sub-app, it does a simple forward jump. 

	push1 exit
	jump
exit:
	jumpdest
	stop
```
The bytecode of `b.etk` is simple: `6003565b00`. The `exit`-label is `03`. 

However, if we compile `a.etk`, we get `6100006003565b00`. `b` is identical, `6003565b00` -- the `exit`-label is _still_ `03`, not adjusted to `06` for the additional preceding `3` bytes. 
 
This behaviour strikes me as _wrong_, but otoh the behaviour of `include` doesn't seem to be documented anywhere, maybe it's intended to be just a "dumb insert"?

**Comment by holiman** [comment]
The "dump insert" behaviour is ideal if it's meant to be used in constructors. 

Less great for inserting functionality into live code. Is there some other mechanism that one can use for the latter usecase?

**Comment by SamWilsn** [comment]
There are two read-another-file-type macros: [`%import`](https://quilt.github.io/etk/ch02-lang/ch04-macros/ch01-builtins.html#import) and [`%include`](https://quilt.github.io/etk/ch02-lang/ch04-macros/ch01-builtins.html#include).

`%import` updates labels, while `%include` creates a new scope and is mostly for constructors.

**Comment by holiman** [comment]
> Is there some other mechanism that one can use for the latter usecase?

Yes: the `import` mechanism. Ok I'll just close this :)

**Comment by holiman** [comment]
> Yes: the `import` mechanism. Ok I'll just close this :)

Doh @SamWilsn beat me to it, that was fast!

**Comment by SamWilsn** [comment]
Just happened to be reviewing a pull request here :sweat_smile:
