### ISSUE TITLE
Labels are misaligned after using push20

### ISSUE THREAD

**Issue by kebian** [quilt/etk#143]
Edited:   I initially thought this bug only happened if you used a push20 in an expression macro but it happens if you use a push20 outside of a macro as well.

Hiya.  Thanks for your work on this assembler. I'm a fan :)

Unfortunately I've come across a small bug where jump instructions to labels can be incorrect if the assembly contains a push20 instruction before the label

```
    push1 my_label
    jump
    push20 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 # this causes the label below to be misaligned
    stop

my_label:
    jumpdest
    push4 0xdeadbeef
    stop
```

This will assemble to `60195673c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2005b63deadbeef00` and then disassemble to the following.
```
1 PUSH1 0x19
2 JUMP
3 PUSH20 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
4 STOP
5 JUMPDEST
6 PUSH4 0xdeadbeef
7 STOP
```

As you can see, the expansion of the `my_label` push is 0x12 (18) bytes out!

Thanks!

**Comment by kebian** [comment]
Using the %push() macro works fine.
```
    push1 my_label
    jump
    %push(0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2) # this works fine
    stop

my_label:
    jumpdest
    push4 0xdeadbeef
    stop```

**Comment by kebian** [comment]
I think my bug report isn't entirely accurate.  Unfortunately I've been in hospital under general anaesthetic today and it's probably affecting my thinking.... I'll reopen with a better report if I'm still having trouble tomorrow.  Sorry for the trouble!

**Comment by SamWilsn** [comment]
Thanks for the report, and I hope you're feeling better! If you do confirm the bug, please let us know :3
