### ISSUE TITLE
Label arbitrary instructions (not just jumpdest)

### ISSUE THREAD

**Issue by lightclient** [quilt/etk#22]
I'd like to be able to write more nasm-like code, something like this:

```asm
.start
    push1 1
    pop
    caller
    jump .start
```

this would expand to:

```
jumpdest
pop
caller
push1 0
jump
```

**Comment by SamWilsn** [comment]
Would you be okay with:

```
.start
    jumpdest
    push1 1
    pop
    caller
    %jump(.start)
```

So you'd still need to type the `jumpdest`, but there'd be a `%jump` macro (name/syntax pending) that inserts the optimal push instruction, and the jump?

I know it's more verbose, but I feel pretty strongly about not auto-generating opcodes.

**Comment by lightclient** [comment]
That seems reasonable. I'm still not quite sure I understand you concern with auto-generating opcodes?
